version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - docker build -t node1:latest .
      - docker tag node1 049810161205.dkr.ecr.ap-southeast-1.amazonaws.com/caoluc_cicd1
  post_build:
    commands:
      - docker push <ECR_URL>
      - printf '[{"name":<TASK_DEFINITION_NAME>,"imageUri":"%s"}]' 049810161205.dkr.ecr.ap-southeast-1.amazonaws.com/caoluc_cicd1 imagedefinitions.json
artifacts:
  files: imagedefinitions.json
